"""
Evaluate Language Detection Accuracy

Measures two things:
  1. Routing accuracy: are episodes indexed in the correct language index?
     (based on RSS <language> tag → target_index mapping)
  2. Content detection accuracy: does detect_language(title + description)
     correctly classify the content language?

Requires a labeled sample file with 'correct_language' and 'routing_correct'
fields (generated by sampling and human review).

Usage:
    python scripts/evaluate_language_detection.py
    python scripts/evaluate_language_detection.py \
        --sample data/evaluation/language_detection_sample.json \
        --output data/evaluation/language_detection_report.json

Thresholds:
    precision >= 95%, recall >= 90%, zh-tw/zh-cn confusion rate < 5%

Known limitations:
    - content detect_language() is binary (zh vs en); cannot distinguish zh-tw from zh-cn
    - labeled sample is 90 episodes (30 per language), human-reviewed 2026-03-25
    - routing errors found: 2/90 shows with wrong RSS language tag routed to en index
"""

import argparse
import json
import re
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Tuple


THRESHOLDS = {
    "precision": 0.95,
    "recall": 0.90,
    "zh_confusion_rate": 0.05,
}


def detect_language(text: str) -> str:
    """Binary language detection: zh or en."""
    if not text:
        return "unknown"
    chinese_chars = len(re.findall(r"[\u4e00-\u9fff]", text))
    total_chars = len(text.replace(" ", ""))
    if total_chars == 0:
        return "unknown"
    return "zh" if chinese_chars / total_chars > 0.3 else "en"


def load_sample(path: Path) -> List[Dict[str, Any]]:
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    missing = [i for i, s in enumerate(data) if "correct_language" not in s]
    if missing:
        raise ValueError(
            f"Sample file missing 'correct_language' on {len(missing)} entries. "
            "Run sampling script with human review first."
        )
    return data


def compute_confusion_matrix(
    samples: List[Dict[str, Any]],
    predicted_key: str,
    true_key: str,
    labels: List[str],
) -> Dict[str, Dict[str, int]]:
    """Rows = true label, cols = predicted label."""
    matrix: Dict[str, Dict[str, int]] = {t: {p: 0 for p in labels} for t in labels}
    for s in samples:
        true = s[true_key]
        pred = s[predicted_key]
        if true in matrix and pred in matrix:
            matrix[true][pred] += 1
    return matrix


def precision_recall(
    matrix: Dict[str, Dict[str, int]], label: str
) -> Tuple[float, float]:
    tp = matrix[label][label]
    fp = sum(matrix[t][label] for t in matrix if t != label)
    fn = sum(matrix[label][p] for p in matrix[label] if p != label)
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    return precision, recall


def evaluate_routing(samples: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Evaluate index routing accuracy (RSS tag → target index)."""
    labels = ["zh-tw", "zh-cn", "en"]

    # Add 'routed_to' field = 'index' (what index the episode is actually in)
    for s in samples:
        s["_routed_to"] = s["index"]

    matrix = compute_confusion_matrix(samples, "_routed_to", "correct_language", labels)

    per_class = {}
    for lang in labels:
        p, r = precision_recall(matrix, lang)
        per_class[lang] = {"precision": round(p, 4), "recall": round(r, 4)}

    # Overall accuracy
    correct = sum(1 for s in samples if s["_routed_to"] == s["correct_language"])
    accuracy = correct / len(samples)

    # zh-tw / zh-cn confusion rate (zh routed to wrong zh index)
    zh_samples = [s for s in samples if s["correct_language"] in ("zh-tw", "zh-cn")]
    zh_confused = sum(
        1 for s in zh_samples
        if s["_routed_to"] in ("zh-tw", "zh-cn") and s["_routed_to"] != s["correct_language"]
    )
    zh_confusion_rate = zh_confused / len(zh_samples) if zh_samples else 0.0

    # Routing errors detail
    errors = [
        {
            "show": s["show_title"],
            "episode": s["episode_title"],
            "correct_language": s["correct_language"],
            "routed_to": s["_routed_to"],
            "rss_language": s["rss_language"],
        }
        for s in samples if s["_routed_to"] != s["correct_language"]
    ]

    return {
        "accuracy": round(accuracy, 4),
        "zh_confusion_rate": round(zh_confusion_rate, 4),
        "per_class": per_class,
        "confusion_matrix": matrix,
        "errors": errors,
        "gate": {
            "precision_min": min(v["precision"] for v in per_class.values()),
            "recall_min": min(v["recall"] for v in per_class.values()),
            "zh_confusion_rate": round(zh_confusion_rate, 4),
        },
    }


def evaluate_content_detection(samples: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Evaluate content-based detect_language() accuracy.

    Note: detect_language() is binary (zh vs en), so zh-tw and zh-cn
    are merged into 'zh' for this evaluation.
    """
    binary_labels = ["zh", "en"]

    results = []
    for s in samples:
        text = s["episode_title"] + " " + s.get("description_snippet", "")
        detected = detect_language(text)
        true_binary = "zh" if s["correct_language"] in ("zh-tw", "zh-cn") else "en"
        results.append({**s, "_detected": detected, "_true_binary": true_binary})

    matrix = compute_confusion_matrix(results, "_detected", "_true_binary", binary_labels)

    per_class = {}
    for lang in binary_labels:
        p, r = precision_recall(matrix, lang)
        per_class[lang] = {"precision": round(p, 4), "recall": round(r, 4)}

    correct = sum(1 for r in results if r["_detected"] == r["_true_binary"])
    accuracy = correct / len(results)

    errors = [
        {
            "show": r["show_title"],
            "episode": r["episode_title"],
            "desc_snippet": r.get("description_snippet", "")[:100],
            "correct_language": r["correct_language"],
            "detected": r["_detected"],
            "true_binary": r["_true_binary"],
        }
        for r in results if r["_detected"] != r["_true_binary"]
    ]

    return {
        "accuracy": round(accuracy, 4),
        "note": "Binary only (zh vs en). Cannot distinguish zh-tw from zh-cn.",
        "per_class": per_class,
        "confusion_matrix": matrix,
        "errors": errors,
        "gate": {
            "precision_min": min(v["precision"] for v in per_class.values()),
            "recall_min": min(v["recall"] for v in per_class.values()),
        },
    }


def gate_status(routing: Dict, detection: Dict) -> str:
    g = routing["gate"]
    if (
        g["precision_min"] >= THRESHOLDS["precision"]
        and g["recall_min"] >= THRESHOLDS["recall"]
        and g["zh_confusion_rate"] <= THRESHOLDS["zh_confusion_rate"]
    ):
        return "PASS"
    return "FAIL"


def print_report(routing: Dict, detection: Dict, n: int) -> None:
    print()
    print("=" * 60)
    print("Language Routing Report")
    print("=" * 60)
    print(f"Sample size: {n} episodes (human-reviewed)")
    print()

    status = gate_status(routing, detection)
    print(f"Overall: {'✅ PASS' if status == 'PASS' else '❌ FAIL'}")
    print()

    print("── Routing Accuracy (RSS tag → index) ─────────────────")
    print(f"  Overall accuracy: {routing['accuracy']:.1%}")
    print(f"  zh-tw/zh-cn confusion rate: {routing['zh_confusion_rate']:.1%}  (threshold < 5%)")
    print()
    print(f"  {'Language':<8} {'Precision':>10} {'Recall':>10}  Thresholds: P≥95%, R≥90%")
    print("  " + "-" * 35)
    for lang, m in routing["per_class"].items():
        p_ok = "✅" if m["precision"] >= THRESHOLDS["precision"] else "❌"
        r_ok = "✅" if m["recall"] >= THRESHOLDS["recall"] else "❌"
        print(f"  {lang:<8} {m['precision']:>9.1%} {p_ok}  {m['recall']:>9.1%} {r_ok}")
    if routing["errors"]:
        print()
        print(f"  Routing errors ({len(routing['errors'])}):")
        for e in routing["errors"]:
            print(f"    [{e['routed_to']}] should be [{e['correct_language']}] | rss={e['rss_language']} | {e['show'][:40]}")

    print()
    print("── Content Detection (detect_language on title+desc) ───")
    print(f"  Overall accuracy: {detection['accuracy']:.1%}  (binary: zh vs en)")
    print(f"  Note: {detection['note']}")
    print()
    for lang, m in detection["per_class"].items():
        print(f"  {lang:<8} precision={m['precision']:.1%}  recall={m['recall']:.1%}")
    if detection["errors"]:
        print()
        print(f"  Detection errors ({len(detection['errors'])}):")
        for e in detection["errors"]:
            print(f"    [{e['detected']}] should be [{e['true_binary']}] | {e['show'][:40]}")
            if e["desc_snippet"]:
                print(f"      desc: {e['desc_snippet']}")

    print()
    print("=" * 60)


def main():
    parser = argparse.ArgumentParser(description="Evaluate language routing accuracy (RSS tag → index)")
    parser.add_argument(
        "--sample",
        type=Path,
        default=Path("data/evaluation/language_detection_sample.json"),
        help="Path to labeled sample JSON",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output path for JSON report",
    )
    args = parser.parse_args()

    samples = load_sample(args.sample)
    print(f"Loaded {len(samples)} labeled samples from {args.sample}")

    routing = evaluate_routing(samples)
    detection = evaluate_content_detection(samples)

    print_report(routing, detection, len(samples))

    if args.output:
        output = {
            "meta": {
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "sample_size": len(samples),
                "sample_file": str(args.sample),
                "thresholds": THRESHOLDS,
                "known_limitations": [
                    "detect_language() is binary (zh vs en), cannot distinguish zh-tw from zh-cn",
                    "sample is 90 episodes, human-reviewed 2026-03-25",
                    "routing errors caused by wrong RSS language tags, not routing logic itself",
                ],
            },
            "overall_gate": gate_status(routing, detection),
            "routing": routing,
            "content_detection": detection,
        }
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with open(args.output, "w", encoding="utf-8") as f:
            json.dump(output, f, ensure_ascii=False, indent=2)
        print(f"Saved to: {args.output}")


if __name__ == "__main__":
    main()
